### ISSUE TITLE
Performance Updates for a high-resolution simulation

### ISSUE THREAD

**Issue by JinsuRhee** [pelahi/NBodylib#4]
* Add an adaptive KDTree routine for a normal FOF search

* Add an adaptive KDTree routine for an OMP domain decomposition

* Node skip routines for FOF search

* Node close routines for FOF search

**Comment by pelahi** [comment]
Hi @JinsuRhee , is there a reason you have just opened an issue? I think you may have incorrectly generated an issue rather than a pull request so I am closing this issue.
